#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{ if .Values.csi.clientEnabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alluxio-pv
  labels:
    name: alluxio-pv
spec:
  accessModes:
  {{ toYaml .Values.csi.accessModes }}
  capacity:
    storage: {{ .Values.csi.quota }}
  csi:
    driver: alluxio
    volumeHandle: alluxio
    volumeAttributes:
      alluxioPath: {{ .Values.csi.alluxioPath }}
      javaOptions: {{ .Values.csi.javaOptions }}
  mountOptions:
  {{- range .Values.csi.mountOptions }}
  - "{{ . }}"
  {{- end }}
{{- end }}
