# {Github | Local | Release}
Type: Local

# github repo and version(can be branch, commit hash)
Github: 
  Repo: https://github.com/amplab/tachyon
  Version: branch-0.5

Release:
  Dist: tachyon-0.5.0-bin.tar.gz
