#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

name: alluxio
apiVersion: v1
description: Open source data orchestration for analytics and machine learning in any cloud.
version: 0.6.27
home: https://www.alluxio.io/
maintainers:
- name: Adit Madan
  email: adit@alluxio.com
- name: Chris Zhu
  email: czhu@alluxio.com
- name: Jiacheng Liu
  email: jiacheng@alluxio.com
- name: Yang Che
  email: cheyang@163.com
