- hosts: all
  tasks:
    - include: roles/common/tasks/main.yml
    - include: roles/lib/tasks/mount.yml
      when: provider == "aws"

    - name: open PasswordAuthentication of sshd for openstack
      replace: >
        dest=/etc/ssh/sshd_config
        regexp='PasswordAuthentication no'
        replace='PasswordAuthentication yes'
      sudo: yes
      when: provider == "os"

- hosts: TachyonMaster
  tasks:
    - include: roles/vagrant_utils/tasks/main.yml

    # Ufs
    - include: roles/ufs_{{ ufs }}/tasks/download_release.yml
    - include: roles/ufs_{{ ufs }}/tasks/config.yml

    # Tachyon
    - include: roles/tachyon/tasks/download_release.yml
      when: (tachyon_type == "Release") and (mesos_type == "None")

    - include: roles/tachyon/tasks/clone_local_repo.yml
      # vb syncs local repo to vm through kernel module instead of rsync
      when: (tachyon_type == "Local") and (provider != "vb") and (mesos_type == "None")

  # TODO uncomment
  #  - include: roles/tachyon/tasks/clone_remote_repo.yml
  #    when: (tachyon_type == "Github") or (mesos_type != "None")

  # TODO uncomment
  #  - include: roles/tachyon/tasks/compile.yml
  #    when: tachyon_type != "Release"

    - include: roles/tachyon/tasks/config.yml

    - include: roles/lib/tasks/tachyon_tiered.yml
      when: (ufs != "hadoop1") and (ufs != "hadoop2")

    # Spark
    - include: roles/spark/tasks/download_release.yml
      when: spark_type == "Release"

    - include: roles/spark/tasks/clone_remote_repo.yml
      when: spark_type == "Github"

    - include: roles/spark/tasks/compile.yml
      when: spark_type == "Github"

    - include: roles/spark/tasks/config.yml
      when: spark_type != "None"

    # Mesos
    - include: roles/mesos/tasks/download_release.yml
      when: mesos_type == "Release"

    - include: roles/mesos/tasks/clone_remote_repo.yml
      when: mesos_type == "Github"

# TODO uncomment
#    - include: roles/mesos/tasks/compile.yml
#      when: mesos_type == "Github"

- hosts: TachyonWorker*
  tasks:
    - include: roles/ufs_{{ ufs }}/tasks/rsync_dist.yml

    - include: roles/tachyon/tasks/rsync_dist.yml

    - include: roles/spark/tasks/rsync_dist.yml
      when: spark_type != "None"

    - include: roles/mesos/tasks/rsync_dist.yml
      when: mesos_type != "None"

- hosts: TachyonMaster
  tasks:
    - include: roles/mesos/tasks/start_master.yml
      when: mesos_type != "None"

- hosts: all
  tasks:
    - include: roles/mesos/tasks/start_slave.yml
      when: mesos_type != "None"

- hosts: TachyonMaster
  tasks:
    - include: roles/ufs_{{ ufs }}/tasks/start.yml

    - include: roles/tachyon/tasks/start.yml
      when: mesos_type == "None"

    - include: roles/tachyon/tasks/start_mesos_framework.yml
      when: mesos_type != "None"

    - include: roles/spark/tasks/start.yml
      when: spark_type != "None"

