- hosts: all
  tasks:
    - include: roles/common/tasks/main.yml
    - include: roles/vagrant_utils/tasks/main.yml

    - include: roles/lib/tasks/mount.yml
      when: provider == "aws"

    - name: open PasswordAuthentication of sshd for openstack
      replace: >
        dest=/etc/ssh/sshd_config
        regexp='PasswordAuthentication no'
        replace='PasswordAuthentication yes'
      sudo: yes
      when: provider == "os"

    # tachyon starts workers at `hostname -f`, in vb, hostname is set by vagrant to TachyonMaster, TachyonWorker1
    # and they are set to "127.0.0.1" in /etc/hosts
    # so, although worker starts at TachyonWorker1, TachyonMaster can not access it because
    # only TachyonMaster.local, TachyonWorker#.local can be accessed among each other in cluster
    # AWS provides hostname that will be resolved to the private network ip that is the same as TachyonMaster,
    # TachyonWorker1, etc.
    - name: set hostname from TachyonXXX to TachyonXXX.local
      shell: sudo hostname `hostname | cut -d'.' -f1`.local # in case provisioning happens more than once
      when: provider == "vb"

- hosts: TachyonMaster
  tasks:
    # Ufs
    - include: roles/ufs_{{ ufs }}/tasks/download_release.yml
    - include: roles/ufs_{{ ufs }}/tasks/config.yml

    # Tachyon
    - include: roles/tachyon/tasks/download_release.yml
      when: tachyon_type == "Release"

    - include: roles/tachyon/tasks/clone_local_repo.yml
      when: (tachyon_type == "Local") and (provider != "vb") # vb syncs local repo to vm through kernel module instead of rsync

    - include: roles/tachyon/tasks/clone_remote_repo.yml
      when: tachyon_type == "Github"

    - include: roles/tachyon/tasks/compile.yml
      when: tachyon_type != "Release"

    - include: roles/tachyon/tasks/config.yml

    # Spark
    - include: roles/spark/tasks/download_release.yml
      when: spark_type == "Release"

    - include: roles/spark/tasks/clone_remote_repo.yml
      when: spark_type == "Github"

    - include: roles/spark/tasks/compile.yml
      when: spark_type == "Github"

    - include: roles/spark/tasks/config.yml
      when: spark_type != "None"

- hosts: TachyonWorker*
  tasks:
    - include: roles/ufs_{{ ufs }}/tasks/rsync_dist.yml

    - include: roles/tachyon/tasks/rsync_dist.yml

    - include: roles/spark/tasks/rsync_dist.yml
      when: spark_type != "None"

- hosts: TachyonMaster
  tasks:
    - include: roles/ufs_{{ ufs }}/tasks/start.yml

    - include: roles/tachyon/tasks/start.yml

    - include: roles/spark/tasks/start.yml
      when: spark_type != "None"

