- hosts: TachyonMaster
  tasks:
    - include: roles/mesos/tasks/start_master.yml

- hosts: all
  tasks:
    - include: roles/mesos/tasks/start_slave.yml

    - include: roles/alluxio/tasks/create_mount.yml

    - include: roles/mesos/tasks/config_tachyon.yml

- hosts: TachyonMaster
  tasks:
    - include: roles/tachyon/tasks/start_mesos_framework.yml
