#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

# Environment setup: network, ssh, mount disk, install development tools, etc.
- hosts: all
  tasks:
    - include: roles/common/tasks/main.yml
    - include: roles/lib/tasks/mount.yml
      when: provider == "aws"

# Download, compile, configure all the cluster components.
- hosts: AlluxioMaster
  tasks:
    - include: roles/vagrant_utils/tasks/main.yml

    # Ufs
    - include: roles/ufs_{{ ufs }}/tasks/download_release.yml

    # Alluxio
    - include: roles/alluxio/tasks/download_release.yml
      when: alluxio_type == "Release"

    - include: roles/alluxio/tasks/clone_local_repo.yml
      # vb syncs local repo to vm through kernel module instead of rsync
      when: (alluxio_type == "Local") and (provider != "vb")

    - include: roles/alluxio/tasks/clone_remote_repo.yml
      when: alluxio_type == "Github"

    - include: roles/alluxio/tasks/compile.yml
      when: alluxio_type != "Release"

    - include: roles/alluxio/tasks/config.yml

    - include: roles/lib/tasks/alluxio_tiered.yml
      when: (ufs != "hadoop1") and (ufs != "hadoop2")

    # some ufs configurations depend on alluxio like alluxio client jar path for hdfs
    - include: roles/ufs_{{ ufs }}/tasks/config.yml

    # Spark
    - include: roles/spark/tasks/download_release.yml
      when: spark_type == "Release"

    - include: roles/spark/tasks/clone_remote_repo.yml
      when: spark_type == "Github"

    - include: roles/spark/tasks/compile.yml
      when: spark_type == "Github"

    - include: roles/spark/tasks/config.yml
      when: spark_type != "None"

    # Mesos
    - include: roles/mesos/tasks/download_release.yml
      when: mesos_type == "Release"

    - include: roles/mesos/tasks/clone_remote_repo.yml
      when: mesos_type == "Github"

    - include: roles/mesos/tasks/compile.yml
      when: mesos_type == "Github"

# Rsync compiled and configured packages to other machines.
- hosts: all
  tasks:
    - include: roles/ufs_{{ ufs }}/tasks/rsync_dist.yml

    - include: roles/alluxio/tasks/rsync_dist.yml

    - include: roles/spark/tasks/rsync_dist.yml
      when: spark_type != "None"

    - include: roles/mesos/tasks/rsync_dist.yml
      when: mesos_type != "None"

# Start UFS.
- hosts: AlluxioMaster
  tasks:
    - include: roles/ufs_{{ ufs }}/tasks/start.yml

# Start Alluxio on the specified platform(e.x. standalone, mesos)
- include: start_alluxio_on_{{ alluxio_platform }}.yml

# Start computation frameworks.
- hosts: AlluxioMaster
  tasks:
    - include: roles/spark/tasks/start.yml
      when: spark_type != "None"
