- name: start alluxio mesos framework
  command: /alluxio/integration/mesos/bin/alluxio-mesos-start.sh AlluxioMaster:50050
  environment:
    ALLUXIO_UNDERFS_ADDRESS: "hdfs://AlluxioMaster:9000/"
  async: 10
  poll: 0

# vim :set filetype=ansible.yaml:
