# For efficiency, only TachyonMaster will compile from source
# other nodes rsync necessary runtime from TachyonMaster
---

- name: install rsync
  yum: name=rsync
  sudo: yes

- name: mkdir /mesos
  script: mkdir.sh

- name: rsync mesos from TachyonMaster
  script: rsync.sh

# vim :set filetype=ansible.yaml: