# EC2 login Keypair
# To get it, refer to information at 
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html
Keypair: "aws-east"

# Path to the ssh key
Key_Path: "~/.ssh/aws-east.pem"

# RHEL 6.5 Amazon Machine Images
AMI: "ami-b06a98d8"

# EC2 network security groups and subnet id
# Ensure ports used by Tachyon are on
# For more information, check out
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html
Security_Group: "test"
Region: "us-east-1"
Availability_Zone: "us-east-1b"

Instance_Type: "m1.small"

# tag to the instance name
# to avoid name conflict during mutiple deployment
Tag: "my-"