# EC2 login Keypair
# To get it, refer to information at 
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html
Keypair: "aws-east"

# Path to the ssh key
Key_Path: "~/.ssh/aws-east.pem"

# RHEL 6.5 Amazon Machine Images
# PV
AMI: "ami-b06a98d8"
# HVM
# AMI: "ami-5b697332"

# EC2 network security groups and subnet id
# Ensure ports used by Tachyon are on
# For more information, check out
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html
Security_Group: "test"
Region: "us-east-1"
Availability_Zone: "us-east-1b"

Instance_Type: "m1.small"

# Block Device Mapping, modify this if you want your instance to have more than
# 10 GB Storage. For more info see:
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html
Block_Device_Mapping: []
#  - DeviceName: "/dev/sda1"
#    VirtualName: "root"
#    Ebs.VolumeSize: "100"
#    Ebs.DeleteOnTermination: "true"

# tag to the instance name
# to avoid name conflict during mutiple deployment
Tag: "my-"
