# Local means copying the Tachyon repo which this directory resides in to remote machines and then compile in remote machines.
# Release means using binary distribution from https://github.com/amplab/tachyon/releases.
# Github means cloning and compiling github repo.
# {Github | Local | Release}
Type: Local

# github repo and version(can be branch, commit hash)
Github:
  Repo: https://github.com/amplab/alluxio
  Version: branch-0.8

Release:
  Version: 0.8.2 # name of release version

# how much memory to use (e.g. 1000MB, 2GB) per worker
# make sure your virtual machine has more memory than what is specified here
#  for virtualbox, machine memory is configured in conf/init.yml:Memory
#  for aws, machine memory is decided by instance type
WorkerMemory: 1GB

# Number of Tachyon masters in the cluster, should be at least 1.
# The cluster will be in fault tolerant mode if the number is larger than 1.
# When it is in fault tolerant mode, the masters will be named as TachyonMaster, TachyonMaster2, etc,
# currently, zookeeper is installed in /zookeeper and is a single node deployment, its server process runs on TachyonMaster.
# This option only has effect when Tachyon is run directly on the host instead of on top of frameworks like mesos or yarn.
Masters: 1
