# Rsync local Tachyon repo(suppose it's under the relative path: playbook.yml/../../../)
---

- name: mkdir /alluxio
  script: mkdir.sh

- name: clone local alluxio repo
  synchronize:
    src: ../../../../../../
    dest: /alluxio
    rsync_opts: >
      --exclude=.gitignore,
      --filter="- /*/target/",
      --filter="- /.git/",
      --filter="- /deploy/",
      --filter="- /docs/",
      --filter="- /journal/",
      --filter="- /logs/",
      --filter="- /target/",
      --filter="- /underFSStorage/"


# vim :set filetype=ansible.yaml:
