# Compile Tachyon, compiling is related to ufs, so will reference scripts in roles/ufs_xxx
---

- include: ../../lib/tasks/maven.yml

# compile_tachyon.sh defined in ufs_xxx/files
- copy: >
    src=roles/ufs_{{ ufs }}/files/compile_tachyon.sh
    dest=/tmp/compile_tachyon.sh

- name: compile alluxio
  shell: bash /tmp/compile_tachyon.sh
  environment:
    HADOOP_VERSION: "{{ hadoop_version }}"
  async: 1200
  poll: 60

# vim :set filetype=ansible.yaml:
