# Configure Tachyon, some configuration is related to ufs, so will reference scripts in roles/ufs_xxx
---

- name: set alluxio/conf/workers
  script: set_workers.sh

- name: set TACHYON_MASTER_ADDRESS in alluxio-env.sh
  script: set_master_address.sh

- name: set ufs related info in alluxio-env.sh
  script: roles/ufs_{{ ufs }}/files/config_tachyon.sh
  environment:
    S3_BUCKET: "{{ s3_bucket }}"
    S3_ID: "{{ s3_id }}"
    S3_KEY: "{{ s3_key }}"

- name: set usezookeeper and zookeeper address if number of masters is larger than 1
  script: zookeeper.sh
  when: tachyon_masters > 1

- name: set journal folder as a shared folder in underfs for fault tolerance
  script: set_journal_folder.sh
  when: tachyon_masters > 1

- name: set longer worker heartbeat timeout to wait for leader selection
  script: set_worker_heartbeat_timeout.sh
  when: tachyon_masters > 1

- name: set worker memory in alluxio-env.sh
  replace: >
    dest=/alluxio/conf/alluxio-env.sh
    regexp='^export TACHYON_WORKER_MEMORY_SIZE=.*'
    replace='export TACHYON_WORKER_MEMORY_SIZE={{ tachyon_memory }}'

- name: let alluxio ssh to workers in parallel when start
  replace: >
    dest=/alluxio/conf/alluxio-env.sh
    regexp='TACHYON_SSH_FOREGROUND="yes"'
    replace='TACHYON_SSH_FOREGROUND=""'

- name: set TACHYON_JAR in libexec/alluxio-config.sh
  script: tachyon_jar.sh

# vim :set filetype=ansible.yaml:
