name: Java 8 Unit Tests

on:
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: "modules: "

    strategy:
      fail-fast: false
      matrix:
        modules:
          - >-
            !alluxio.client.**,!alluxio.master.**
          - >-
            alluxio.client.**,alluxio.master.**

    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, 'DOCFIX') &&
        !contains(github.event.pull_request.title, 'SKIPCI')"

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.11.0'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Run tests
        id: test0
        run: |
          mkdir -p ~/.m2
          ALLUXIO_DOCKER_NO_TTY=true \
          ALLUXIO_DOCKER_GIT_CLEAN=true \
          ALLUXIO_DOCKER_MVN_RUNTOEND=true \
          ALLUXIO_DOCKER_MVN_PROJECT_LIST=!webui,!shaded/client,!assembly/client,!assembly/server \
          dev/github/run_docker.sh "\"-Dtest=${{ matrix.modules }}\"" -pl '!tests,!webui'
        timeout-minutes: 60
      - name: Generate coverage report
        id: cov0
        if: always()
        run: |
          mkdir -p ~/.m2
          ALLUXIO_DOCKER_NO_TTY=true \
          ALLUXIO_COVERAGE_REPORT=true \
          ALLUXIO_DOCKER_MVN_RUNTOEND=true \
          ALLUXIO_DOCKER_MVN_PROJECT_LIST=!webui,!shaded/client,!shaded/hadoop,!shaded/ozone,!integration/tools/hms,!integration/yarn,!assembly/client,!assembly/server,!table/server/underdb/glue,!table/server/underdb/hive,!underfs/hdfs,!underfs/ozone,!underfs/adl,!underfs/wasb,!underfs/cos,!underfs/kodo,!underfs/oss,!underfs/swift \
          dev/github/run_docker.sh
        timeout-minutes: 60

      - name: Archive artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: artifact
          path: |
            **/target/surefire-reports/*
            **/target/artifacts/*
            **/target/logs/*
          retention-days: 7
      - name: "Upload Code Coverage Report"
        uses: codecov/codecov-action@v1
        if: always()
        with:
          file: ./**/target/site/jacoco/jacoco.xml # optional
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
