name: Java 11 Unit Tests (w/ webui)

on: [pull_request]

jobs:
  build:
    name: "modules: "

    strategy:
      fail-fast: false
      matrix:
        modules:
          - >-
            **

    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, 'DOCFIX') &&
        !contains(github.event.pull_request.title, 'SKIPCI')"

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.11.0'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Run tests
        id: test0
        run: |
          mkdir -p ~/.m2
          ALLUXIO_DOCKER_NO_TTY=true \
          ALLUXIO_DOCKER_GIT_CLEAN=true \
          ALLUXIO_DOCKER_MVN_RUNTOEND=true \
          ALLUXIO_DOCKER_MVN_PROJECT_LIST=!shaded/client,!assembly/client,!assembly/server \
          ALLUXIO_DOCKER_IMAGE=alluxio/alluxio-maven:0.0.6-jdk11 \
          dev/github/run_docker.sh "\"-Dtest=${{ matrix.modules }}\"" -pl 'webui'
        timeout-minutes: 60

      - name: Archive artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: artifact
          path: |
            **/target/artifacts/*
            **/target/logs/*
            log*
          retention-days: 7
