name: Java 8 Fault Tolerant Integration Tests

# This build runs the fault tolerance specific integration tests in the dora/tests module
# The key differences between this build and the default integration test build are
# - Only runs integration tests with prefix alluxio.server.ft
# - Sets fork count to 1 to prevent flakey errors due to running concurrent tests; default count is 2

on: [pull_request]

jobs:
  build:
    name: "modules: "

    strategy:
      fail-fast: false
      matrix:
        modules:
          - >-
            alluxio.server.ft.**,!alluxio.server.ft.journal.raft.**,!alluxio.server.ft.journal.ufs.**
          - >-
            alluxio.server.ft.journal.raft.**,alluxio.server.ft.journal.ufs.**

    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, 'DOCFIX') &&
        !contains(github.event.pull_request.title, 'SKIPCI')"

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.11.0'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-java11-${{ hashFiles('**/pom.xml') }}

      - name: Cache local Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.mod') }}

      - name: Run tests
        id: test0
        run: |
          mkdir -p ~/.m2
          # Set fork count to 1 so that fault tolerant tests are run sequentially as these tests have high overhead, starting and stopping multiple Alluxio processes
          ALLUXIO_DOCKER_FORK_COUNT=1 \
          ALLUXIO_DOCKER_NO_TTY=true \
          ALLUXIO_DOCKER_GIT_CLEAN=true \
          ALLUXIO_DOCKER_MVN_PROJECT_LIST=dora/tests/integration \
          ALLUXIO_DOCKER_MVN_TESTS=${{ matrix.modules }} \
          dev/github/run_docker.sh
        timeout-minutes: 60

      - name: Archive artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifact
          path: |
            **/target/surefire-reports/*
            **/target/artifacts/*
            **/target/logs/*
          retention-days: 7
