name: Java 8 Integration Tests

on: [pull_request]

jobs:
  build:
    name: "Test modules: "

    strategy:
      fail-fast: false
      matrix:
        modules:
          - >-
            alluxio.client.cli.**
          - >-
            alluxio.client.fs.**
          - >-
            alluxio.client.**,!alluxio.client.fs.**,!alluxio.client.cli.**
          - >-
            alluxio.job.**
          - >-
            alluxio.master.**
          - >-
            alluxio.server.ft.**
          - >-
            alluxio.server.**,!alluxio.server.ft.**
          - >-
            alluxio.web.**

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.11.0'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        continue-on-error: true
        id: test0
        run: |
          mkdir -p ~/.m2
          ALLUXIO_DOCKER_NO_TTY=true \
          ALLUXIO_DOCKER_GIT_CLEAN=true \
          ALLUXIO_DOCKER_MVN_RUNTOEND=true \
          dev/github/run_docker.sh "\"-Dtest=${{ matrix.modules }}\"" -pl tests
        timeout-minutes: 60

      - name: Run tests (Retry 1)
        continue-on-error: true
        id: test1
        if: steps.test0.outcome == 'failure'
        run: |
          mkdir -p ~/.m2
          ALLUXIO_DOCKER_NO_TTY=true \
          ALLUXIO_DOCKER_GIT_CLEAN=true \
          ALLUXIO_DOCKER_MVN_RUNTOEND=true \
          dev/github/run_docker.sh "\"-Dtest=${{ matrix.modules }}\"" -pl tests
        timeout-minutes: 60

      - name: Run tests (Retry 2)
        id: test2
        if: steps.test1.outcome == 'failure'
        run: |
          mkdir -p ~/.m2
          ALLUXIO_DOCKER_NO_TTY=true \
          ALLUXIO_DOCKER_GIT_CLEAN=true \
          ALLUXIO_DOCKER_MVN_RUNTOEND=true \
          dev/github/run_docker.sh "\"-Dtest=${{ matrix.modules }}\"" -pl tests
        timeout-minutes: 60

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: artifact
          path: |
            **/target/artifacts/*
            **/target/logs/*
            log*
          retention-days: 7
