name: Java 8 Integration Tests (w/ webui)

# This build runs the integration tests in the dora/tests module that require the web UI
# The key differences between this build and the default integration test build are
# - Only runs integration tests with prefix alluxio.web
# - Adds webui to the project list

on: [pull_request]

jobs:
  build:
    name: "modules: "

    strategy:
      fail-fast: false
      matrix:
        modules:
          - >-
            alluxio.web.**

    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, 'DOCFIX') &&
        !contains(github.event.pull_request.title, 'SKIPCI')"

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.11.0'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-java11-${{ hashFiles('**/pom.xml') }}

      - name: Cache local Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.mod') }}

      - name: Run tests
        id: test0
        run: |
          mkdir -p ~/.m2
          ALLUXIO_DOCKER_NO_TTY=true \
          ALLUXIO_DOCKER_GIT_CLEAN=true \
          ALLUXIO_DOCKER_MVN_PROJECT_LIST=dora/tests/integration,webui \
          ALLUXIO_DOCKER_MVN_TESTS=${{ matrix.modules }} \
          dev/github/run_docker.sh
        timeout-minutes: 60

      - name: Archive artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifact
          path: |
            **/target/surefire-reports/*
            **/target/artifacts/*
            **/target/logs/*
          retention-days: 7
